from typing import Mapping, Set

DAYS = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
]

COLORS: Mapping[str, str] = {
    # these can come from either https://picular.co/
    # or https://alexbeals.com/projects/colorize/
    "alfredo sauce": "#F2D690",
    "allpurpose flour": "#FCF4EC",
    "amaranth": "#BE9669",
    "apples": "#D1192D",
    "arborio": "#FCF8E1",
    "arugula": "#6C7D3F",
    "avocado": "#B4B453",
    "bacon": "#D95328",
    "bagel": "#E3D3BE",
    "baharat": "#B97B4B",
    "balsamic vinegar": "#715736",
    "basil pesto": "#E8EFB6",
    "bay leaves": "#6F6D34",
    "beans": "#B9856C",
    "beets": "#D3246D",
    "bell peppers": "#FB9109",
    "broccoli": "#445715",
    "brussels sprouts": "#84A64D",
    "bulgur wheat": "#E1AF80",
    "butter": "#F0CA5D",
    "butternut squash": "#D27E30",
    "canadian bacon": "#EEBEA6",
    "carrots": "#F6700A",
    "cauliflower": "#BCAE65",
    "chicken fajitas": "#E6AE83",
    "chickpeas": "#F2C792",
    "coconut milk": "#F3F3F3",
    "coconut oil": "#FCF1E0",
    "coconut sugar": "#B68860",
    "coriander": "#AF8956",
    "cucumber": "#A2B562",
    "cumin": "#B57744",
    "dukkah spice": "#AF8666",
    "egg": "#F3C114",
    "eggs": "#F3C114",
    "fancy bread": "#E4CAA3",
    "fancy cheese": "#FAC114",
    "farro": "#B38A5F",
    "flour": "#FCF4EC",
    "fresh mozzarella balls": "#FCEBBE",
    "fusilli": "#EDC995",
    "garam masala": "#A46944",
    "garlic": "#EDE0D6",
    "ginger": "#C6B038",
    "gnocchi": "#ECDAAD",
    "green olives": "#A8A60D",
    "green onion": "#E0E7B6",
    "green onions": "#7B9557",
    "ground beef": "#CC1D34",
    "hearts of palm": "#DACBAF",
    "italian seasoning": "#C87549",
    "lemon juice": "#F4C710",
    "lemon": "#F4C710",
    "lentils": "#B89548",
    "lettuce": "#A0C845",
    "lime": "#9ABB40",
    "linguine pasta": "#F9E08C",
    "marinara sauce": "#E81721",
    "mayonnaise": "#FCF4D4",
    "mexican seasoning": "#C5673A",
    "milk": "#FCFCF7",
    "mint": "#405A07",
    "mozzarella cheese": "#FCEBBE",
    "mushroom powder": "#CCB494",
    "mushrooms": "#9D7F63",
    "olive oil": "#E8BB10",
    "olives": "#A8A60D",
    "onion": "#DFCE9F",
    "onions": "#DFCE9F",
    "oregano": "#214708",
    "pancetta": "#CE3467",
    "parmesan cheese": "#FCD984",
    "parmesan crisps": "#F7D17A",
    "parmesan": "#E1C520",
    "parsley": "#6FA921",
    "pepper": "#877D75",
    "pita bread": "#EFD2A8",
    "pizza dough": "#DCD1BD",
    "pork tenderloin": "#E3B28E",
    "potatoes": "#F4D476",
    "quinoa": "#C5904A",
    "ras el hanout": "#CB7328",
    "ravioli": "#F0CA87",
    "red lentils": "#AC5633",
    "red paprika powder": "#C0381C",
    "rice": "#EDE5D7",
    "roasted red peppers": "#A70605",
    "rosemary": "#4C5D1E",
    "sage": "#588470",
    "salt": "#B9B8B7",
    "shredded cheese": "#F3BC2A",
    "shredded chicken": "#FCDBB8",
    "shredded mozzarella cheese": "#FCEBBE",
    "shredded parmesan cheese": "#FCF2CB",
    "sliced cheese": "#FCDC7C",
    "smoked turkey breast": "#E9BA9A",
    "soylent": "#FFFFFF",
    "split peas": "#8A9A49",
    "sweet potatoes": "#EA8535",
    "tahini": "#FCDCBF",
    "thyme": "#829C65",
    "tomato paste": "#9D1213",
    "tomatoes": "#F33D0F",
    "tortellini": "#F9E08C",
    "tortilla wrap": "#E9C490",
    "tortillas": "#EFD2A8",
    "turkey breast": "#EFBF83",
    "turmeric": "#F8A00A",
    "vegetable broth": "#C28431",
    "water": "#3C719C",
    "white wine": "#F2D793",
    "zaatar": "#AF8A52",
}

COMMON_INGREDIENTS: Set[str] = {
    "olive oil",
    "pepper",
    "salt",
    "water",
}
